### ISSUE TITLE
Back port from capistrano-rbenv to follow sshkit update?

### ISSUE THREAD

**Issue by ryoqun** [platanus/capistrano-nodenv#3]
I'm sure capistrano-nodenv doesn't work with latest sshkit...

Ref: https://github.com/capistrano/rbenv/pull/59

**Comment by blackjid** [comment]
Would you please provide a PR? that would be awesome.. :)

**Comment by ryoqun** [comment]
@blackjid Hi, I just created a pull request for this! https://github.com/platanus/capistrano-nodenv/pull/4

**Comment by ryoqun** [comment]
@blackjid oh, you're super quick.. :)

**Comment by ryoqun** [comment]
thx!
